site_name: Stefania 
site_url: https://mydomain.org/mysite

theme:
  palette:
    scheme: default
    primary: teal
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: index.md
  - Documentazione:
     - docum/30gen/30gen.md
     - docum/31gen/31gen.md
  - Tags: tags.md
